name: Windows

on:
  pull_request:
  push:
    branches:
      - feature/3_windows-build-using-gha

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-executables:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.6-release
          tag: 5.6-RELEASE
      - uses: actions/checkout@v2
      - run: git config --global core.protectNTFS false
      - run: swift build -c release --static-swift-stdlib --product ReadingTimeCLI
      - run: cmd /r dir /s /b /o:gn
      - run: cp .build\release\ReadingTimeCLI.exe ReadingTimeCLI.exe
      - uses: actions/upload-artifact@v3
        with:
          name: ReadingTimeCLI-windows.exe
          path: ReadingTimeCLI.exe
